"""Editorial content API of the public site.

Reads are open proxies onto PR_API (`GET /site-content/<space>`), because the
règlement is public. Writes are gated twice: `@require_admin` checks the
administrator's own site session here, and PR_API re-checks that the service
token carries `admin.content.manage`. Neither gate is trusted alone.

Images are the one thing that does **not** live in PR_API: the bytes are
written to the `content_uploads` volume mounted on this container and served
back from `/uploads/`, and only a registry row (name, size, author) goes to
PR_API so the editor can list what exists.
"""

import mimetypes
import os
import re
import secrets
import unicodedata

import requests
from flask import Blueprint, abort, jsonify, request, send_from_directory

from auth_guard import admin_actor_headers, require_admin
from content_markdown import render as render_markdown
from pr_api_service_auth import service_auth_headers
from settings import (
    ALLOWED_IMAGE_TYPES,
    MAX_UPLOAD_BYTES,
    PR_API_URL,
    UPLOADS_DIR,
)

content_bp = Blueprint("content", __name__)

CONTENT_SPACES = ("rules", "context", "forum_rp")

# Stored names are generated by us, but the route parameter is not — a filename
# is only ever served if it matches the shape we generate.
_STORED_NAME = re.compile(r"^[0-9a-f]{32}(?:-[a-z0-9-]{1,60})?\.[a-z0-9]{2,5}$")


# ── PR_API plumbing ─────────────────────────────────────────────────────────


def _api(method: str, endpoint: str, *, admin: bool = False, **kwargs):
    headers = kwargs.pop("headers", {}) or {}
    if admin:
        headers = {**headers, **service_auth_headers(), **admin_actor_headers()}
    return requests.request(
        method, f"{PR_API_URL}{endpoint}", timeout=15, headers=headers, **kwargs
    )


def _relay(resp):
    """Forward PR_API's answer, keeping its status code."""
    try:
        payload = resp.json()
    except ValueError:
        return (
            jsonify({"success": False, "error": "Invalid response from PR_API"}),
            502,
        )
    return jsonify(payload), resp.status_code


def _proxy(method: str, endpoint: str, *, admin: bool = False, json_body=None):
    try:
        return _relay(_api(method, endpoint, admin=admin, json=json_body))
    except requests.RequestException as e:
        return jsonify({"success": False, "error": str(e)}), 502


def fetch_space(space: str, include_unpublished: bool = False) -> dict:
    """Server-side read used by the page renderer. Never raises."""
    if space not in CONTENT_SPACES:
        return {"space": space, "categories": []}
    try:
        params = {"drafts": "1"} if include_unpublished else None
        resp = _api("GET", f"/site-content/{space}", params=params)
        if resp.status_code != 200:
            return {"space": space, "categories": [], "unavailable": True}
        payload = resp.json()
        if not payload.get("success"):
            return {"space": space, "categories": [], "unavailable": True}
        return payload.get("data") or {"space": space, "categories": []}
    except (requests.RequestException, ValueError):
        # A page whose content service is down still renders its shell rather
        # than 500ing — the règlement being briefly empty beats an error page.
        return {"space": space, "categories": [], "unavailable": True}


def render_space(space: str, include_unpublished: bool = False) -> dict:
    """`fetch_space` with every body pre-rendered to HTML for the template."""
    data = fetch_space(space, include_unpublished=include_unpublished)
    for category in data.get("categories", []):
        category["summary_html"] = render_markdown(category.get("summary") or "")
        for section in category.get("sections", []):
            section["body_html"] = render_markdown(section.get("body") or "")
            section["callout_html"] = render_markdown(section.get("callout_body") or "")
    return data


# ── Public reads ────────────────────────────────────────────────────────────


@content_bp.route("/api/content/<space>")
def get_space(space):
    if space not in CONTENT_SPACES:
        return jsonify({"success": False, "error": "Unknown content space"}), 404
    return _proxy("GET", f"/site-content/{space}")


@content_bp.route("/api/content/media")
def list_media():
    return _proxy("GET", "/site-content/media")


@content_bp.route("/uploads/<path:filename>")
def serve_upload(filename):
    """Serve an uploaded image from the volume.

    `send_from_directory` already refuses to escape the directory; the name
    shape check on top means a request can only ever name a file this service
    itself created.
    """
    if not _STORED_NAME.match(filename):
        abort(404)
    if not (UPLOADS_DIR / filename).is_file():
        abort(404)
    return send_from_directory(UPLOADS_DIR, filename)


# ── Preview ─────────────────────────────────────────────────────────────────


@content_bp.route("/api/content/preview", methods=["POST"])
@require_admin
def preview():
    """Render markdown exactly as the published page will render it.

    The editor calls this instead of carrying its own renderer, so what the
    administrator previews is what visitors get — byte for byte.
    """
    data = request.get_json(silent=True) or {}
    return jsonify({"success": True, "html": render_markdown(data.get("body") or "")})


# ── Category writes ─────────────────────────────────────────────────────────


@content_bp.route("/api/admin/content/<space>/categories", methods=["POST"])
@require_admin
def create_category(space):
    if space not in CONTENT_SPACES:
        return jsonify({"success": False, "error": "Unknown content space"}), 404
    return _proxy(
        "POST",
        f"/site-content/{space}/categories",
        admin=True,
        json_body=request.get_json(silent=True) or {},
    )


@content_bp.route("/api/admin/content/categories/<int:category_id>", methods=["PUT"])
@require_admin
def update_category(category_id):
    return _proxy(
        "PUT",
        f"/site-content/categories/{category_id}",
        admin=True,
        json_body=request.get_json(silent=True) or {},
    )


@content_bp.route("/api/admin/content/categories/<int:category_id>", methods=["DELETE"])
@require_admin
def delete_category(category_id):
    return _proxy("DELETE", f"/site-content/categories/{category_id}", admin=True)


@content_bp.route("/api/admin/content/<space>/categories/reorder", methods=["POST"])
@require_admin
def reorder_categories(space):
    if space not in CONTENT_SPACES:
        return jsonify({"success": False, "error": "Unknown content space"}), 404
    return _proxy(
        "POST",
        f"/site-content/{space}/categories/reorder",
        admin=True,
        json_body=request.get_json(silent=True) or {},
    )


# ── Section writes ──────────────────────────────────────────────────────────


@content_bp.route(
    "/api/admin/content/categories/<int:category_id>/sections", methods=["POST"]
)
@require_admin
def create_section(category_id):
    return _proxy(
        "POST",
        f"/site-content/categories/{category_id}/sections",
        admin=True,
        json_body=request.get_json(silent=True) or {},
    )


@content_bp.route("/api/admin/content/sections/<int:section_id>", methods=["PUT"])
@require_admin
def update_section(section_id):
    return _proxy(
        "PUT",
        f"/site-content/sections/{section_id}",
        admin=True,
        json_body=request.get_json(silent=True) or {},
    )


@content_bp.route("/api/admin/content/sections/<int:section_id>", methods=["DELETE"])
@require_admin
def delete_section(section_id):
    return _proxy("DELETE", f"/site-content/sections/{section_id}", admin=True)


@content_bp.route(
    "/api/admin/content/categories/<int:category_id>/sections/reorder", methods=["POST"]
)
@require_admin
def reorder_sections(category_id):
    return _proxy(
        "POST",
        f"/site-content/categories/{category_id}/sections/reorder",
        admin=True,
        json_body=request.get_json(silent=True) or {},
    )


# ── Image uploads ───────────────────────────────────────────────────────────


def _slugify_name(name: str) -> str:
    stem = os.path.splitext(name or "")[0]
    normalized = unicodedata.normalize("NFKD", stem)
    ascii_only = normalized.encode("ascii", "ignore").decode("ascii").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_only).strip("-")
    return slug[:60]


def _detect_extension(stream_head: bytes, declared_mime: str, filename: str):
    """(mime, extension) from the magic bytes — the declared type is a hint only.

    A browser will happily send `image/png` for an HTML file; what decides is
    what the first bytes actually are.
    """
    signatures = (
        (b"\x89PNG\r\n\x1a\n", "image/png"),
        (b"\xff\xd8\xff", "image/jpeg"),
        (b"GIF87a", "image/gif"),
        (b"GIF89a", "image/gif"),
    )
    for magic, mime in signatures:
        if stream_head.startswith(magic):
            return mime, ALLOWED_IMAGE_TYPES[mime]
    if stream_head[:4] == b"RIFF" and stream_head[8:12] == b"WEBP":
        return "image/webp", ALLOWED_IMAGE_TYPES["image/webp"]
    if stream_head[4:8] == b"ftyp" and b"avif" in stream_head[8:24]:
        return "image/avif", ALLOWED_IMAGE_TYPES["image/avif"]

    # No recognised signature: refuse rather than trust the declared type.
    guessed = declared_mime or mimetypes.guess_type(filename or "")[0] or ""
    return None, guessed


@content_bp.route("/api/admin/content/media", methods=["POST"])
@require_admin
def upload_media():
    """Store an image in the uploads volume and register it in PR_API."""
    upload = request.files.get("file")
    if upload is None or not upload.filename:
        return jsonify({"success": False, "error": "Aucun fichier reçu"}), 400

    head = upload.stream.read(32)
    upload.stream.seek(0)
    mime, extension = _detect_extension(head, upload.mimetype or "", upload.filename)
    if mime is None:
        return (
            jsonify(
                {
                    "success": False,
                    "error": "Format non reconnu — PNG, JPEG, WebP, GIF ou AVIF "
                    "uniquement (le SVG est refusé : il peut porter du script).",
                }
            ),
            415,
        )

    UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
    slug = _slugify_name(upload.filename)
    stored_name = f"{secrets.token_hex(16)}{'-' + slug if slug else ''}{extension}"
    destination = UPLOADS_DIR / stored_name

    written = 0
    try:
        with open(destination, "wb") as target:
            while True:
                chunk = upload.stream.read(64 * 1024)
                if not chunk:
                    break
                written += len(chunk)
                if written > MAX_UPLOAD_BYTES:
                    raise ValueError("too large")
                target.write(chunk)
    except ValueError:
        destination.unlink(missing_ok=True)
        limit_mb = MAX_UPLOAD_BYTES // (1024 * 1024)
        return (
            jsonify({"success": False, "error": f"Image trop lourde (max {limit_mb} Mo)"}),
            413,
        )
    except OSError as e:
        destination.unlink(missing_ok=True)
        return jsonify({"success": False, "error": f"Écriture impossible : {e}"}), 500

    try:
        resp = _api(
            "POST",
            "/site-content/media",
            admin=True,
            json={
                "filename": stored_name,
                "original_name": upload.filename[:255],
                "mime_type": mime,
                "size_bytes": written,
                "alt_text": (request.form.get("alt") or "")[:400] or None,
            },
        )
    except requests.RequestException as e:
        # The registry row is what makes the file findable again; without it the
        # file is an orphan, so roll the write back rather than leak bytes.
        destination.unlink(missing_ok=True)
        return jsonify({"success": False, "error": str(e)}), 502

    if resp.status_code >= 400:
        destination.unlink(missing_ok=True)
        return _relay(resp)

    payload = resp.json().get("data", {})
    payload["url"] = f"/uploads/{stored_name}"
    payload["markdown"] = f"![{request.form.get('alt') or ''}](/uploads/{stored_name})"
    return jsonify({"success": True, "data": payload}), 201


@content_bp.route("/api/admin/content/media/<int:media_id>", methods=["DELETE"])
@require_admin
def delete_media(media_id):
    """Unregister the image, then remove the file it pointed at."""
    try:
        resp = _api("DELETE", f"/site-content/media/{media_id}", admin=True)
    except requests.RequestException as e:
        return jsonify({"success": False, "error": str(e)}), 502
    if resp.status_code >= 400:
        return _relay(resp)

    filename = (resp.json().get("data") or {}).get("filename") or ""
    if _STORED_NAME.match(filename):
        (UPLOADS_DIR / filename).unlink(missing_ok=True)
    return _relay(resp)
